### ISSUE TITLE
`UNITY_VERTEX_INPUT_INSTANCE_ID` should be `UNITY_INSTANCE_ID` in Unity 5.4

### ISSUE THREAD

**Issue by pharan** [traggett/UnitySpriteShaders#1]
Unity 5.4.2:

Shader error in 'Hidden/Internal-SpriteDepthNormalsTexture': unrecognized identifier 'UNITY_VERTEX_INPUT_INSTANCE_ID' at line 213 (on d3d11)

Compiling Vertex program
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING

**Comment by traggett** [comment]
Ooh hmm, I've been on the 5.5 beta and guessing the UNITY_VERTEX_INPUT_INSTANCE_ID is correct for that? I'm not getting that error message.
Since 5.5 is now out I guess maybe this is no longer an issue? I think it prob makes sense to make it so the shaders always require the latest version of Unity.

**Comment by pharan** [comment]
Unity auto-updates shader code though so it's also fine for 5.5 to leave it at the 5.4 compatibility level. This is up to you though. I've applied the change on the Spine bundled version anyway.
