### ISSUE TITLE
Normals are flipped incorrectly when sprite is flipped via scale or rotation in Unity 2017.4.0f1

### ISSUE THREAD

**Issue by Clement-E-Todd** [traggett/UnitySpriteShaders#14]
Hello, I added a comment on this old issue which seems to have come back (#2), but perhaps it makes more sense to simply open a new issue.

Basically, I'm noticing lighting errors in Unity 2017.4.0f1 when I flip sprites in any way.

![lighting error](https://user-images.githubusercontent.com/2318146/38516739-f208d112-3c05-11e8-94ba-82205ff25759.png)

The statue on the right is scaled (-1, 1, 1). As you can see, the light is hitting it correctly horizontally, but it has been flipped vertically. I tied flipping the sprite in a few different ways (scaling the X axis, rotating on the Y axis, toggling flipX in the sprite renderer). The results were the same as seen above when scaling and rotating, and it was mentioned in the linked issue that flipX is not supported.

Here is how my material is set up:

![lighting error inspector](https://user-images.githubusercontent.com/2318146/38516752-f891609e-3c05-11e8-9834-3fcc9e54ea67.png)

I'm loving the asset aside from this, so hopefully this can get sorted so that I don't have to create separate normal maps for flipped sprites as a work-around. ;)

**Comment by traggett** [comment]
Hey! Are you using the latest shaders in GitHub or from the Asset Store? And are you using Unity Sprites or Quads / Spine animations or something else?

**Comment by Clement-E-Todd** [comment]
Hello! The issue exists in the latest versions on both the Asset Store and this git repo (I started with the Asset Store version and then pulled the latest GitHub revision to see if it would help). I'm just using standard Unity sprites with a SpriteRenderer component.

**Comment by traggett** [comment]
Hey tried recreating and couldn't with just negative X scaling - the lighting appeared correct with just setting the x scale to -1.
I did notice the lighting is incorrect if you use the Flip flags on the Sprite Renderer, I'm trying to figure out what unity does behind the scenes but at the moment there is no way for the shader to know the sprite has been flipped so can't reverse the normals

**Comment by Clement-E-Todd** [comment]
Thanks for looking into it. I'll try to create a small sample project to demonstrate the issue, if that would help (I may not be able to get around to it in the next couple of days though).

I suppose it's also worth noting that I've only tested with directional lights, but I don't imagine that the type of light would make a difference.

**Comment by Clement-E-Todd** [comment]
Hi @traggett I've prepared a sample project that recreates the scenario in my first screenshot above. The project contains a scene with two statues: the one on the right is flipped and the one on the left is not. The scene contains a single directional light source pointing down and to the right.

Assuming that you're using Unity 2017.4.0f1, you should see that both statues are correctly lit from the left, but the statue that is flipped appears to be lit from below, which is incorrect.

You can grab the project here:
[Statues.zip](https://github.com/traggett/UnitySpriteShaders/files/1920730/Statues.zip)

**Comment by traggett** [comment]
Dude. This is one of the weirdest bugs I've come across in Unity!
It might be because I've got a cold at the mo so brains fuzzy but can't work out what's going on at all.
So basically that material is fucked - if I make a new material with the exact same shader / textures / parameters the lighting works correctly.
If I even duplicate mat_goddess.mat and apply that material the lighting is correct!!
I tried comparing the materials in a text editor and there are no differences yet in the original one the lighting is upside down!!

I have no idea whatsoever what's causing it  I'm afraid, thought it might be a corrupted library but cleaning that didn't help  😨 
But yeah a new material worked for me...

**Comment by Clement-E-Todd** [comment]
Hmmm, interesting! That gives me a theory though: before I was using these shaders, I was using shaders from another asset that I had found on the Unity asset store. When I made the switch to your shaders, I didn't create new materials, I simply updated the existing materials to use your shaders and adjusted the metadata until it looked good.

I'm not sure why or how this would happen, but perhaps something from the old metadata carried over and is causing problems? Whenever I have the chance over the next couple of days, I'll try recreating the materials from scratch in the context of my game. I'll let you know if that fixes it so we can close the issue! Thanks for taking the time to look into this, I really appreciate it.

**Comment by Clement-E-Todd** [comment]
Okay, so this is really weird. I have a scene in my game with a bunch of these statues arranged in rows. I tried creating a new material from scratch and it appeared to be working at first as I applied it to each statue one at a time, but then I noticed that if I applied the material to too many statues the lighting would break. See the video here: https://youtu.be/LgVs4hzzl_o

**Comment by traggett** [comment]
Hey so I was poking around with this some more and think all this weirdness comes from how Unity generates meshes for Sprite Renderers behind the scenes.
Bit of a long read but explains all this weirdness! 

So the trouble is to work out normals from a normal map you need to know if a model has any negative scaling because you need to flip the binormals if it does (or rather an odd amount of axis have negative scale).

For normal meshes (3d models / quads etc) this is super easy - Unity sets unity_WorldTransformParams.w to -1 if the model has an odd number of negatively scaled axes or 1 if not.

Sprite Renderers are weird though. Thier meshes get generated automatically by Unity, which I believe are batched so they can be rendered in one go and use custom sorting based on layering orders etc.

As they get combined the negative scale doesnt really make sense - If you have two SpriteRenderers using the same atlas, one with negative x scale or flipped on X and the other not, then Unity will combine them in to one big mesh.

As such there is no way of knowing that one of them should have flipped binormals!!

The only solution is to get Unity to add normals and tangents to the SpriteRenderer - this would mean when it generates its meshes the tangent.w would be set to -1 on any Sprites that have negative scale or flipped along X.
I have my doubts whether Unity will actually do this though as they've said in the past SpriteRenders are not supposed to be affected by dynamic lighting 😢 

For my own games/projects I use Spine which generates meshes in the same way Unity SpriteRenderers do but with optional tangents as well so it all just works 😃 

If enough people wanted it then could try lobbying Unity to allow sprite renderers to optionally include normals and tangents.

**Comment by Clement-E-Todd** [comment]
Aaah okay it makes sense if it's a batching issue... I'll close this issue for now because sadly it doesn't sound like there's solution that can be implemented within the shaders. If I manage to find an acceptable workaround going forward, I'll try and remember to post what I did here for the sake of anyone who stumbles on this thread in the future. 😄 

Thanks again for taking the time to dig into this! Even if we didn't manage to find a solution it will help me to understand the issue going forward.

**Comment by traggett** [comment]
Yeah no worries!
Another solution at the mo is to use something other than SpriteRenderer components to generate the meshes.
TexturePackerPro (https://www.codeandweb.com/texturepacker) is pretty good at it - you can generate a sprite atlas from images and then use them to generate meshes inUnity easily and they have normals and tangents so will just work :)

Have a look at this thread: https://forum.unity.com/threads/texturepacker-importer-spritesheet-generator-sprite-mesh-optimizer.367738/

**Comment by HarmWebnit** [comment]
I had the same problem, found a solution that worked great for my character.

First I inverted the normal map in photoshop (https://www.youtube.com/watch?v=U2vNX-BoRX4)
Than when i flip my character in my script I also change the normal map to the inverted normal map.

Hope this helps in your case as well.
