### ISSUE TITLE
Updating to 2018.1

### ISSUE THREAD

**Issue by mikegeig** [traggett/UnitySpriteShaders#15]
Nice shaders! This isn't an "issue" but I wanted to let you know how to fix an error that pops up in 2018.1. We've changed this line:
`float attenuation = LIGHT_ATTENUATION(input);`
And you can update it to be:
`UNITY_LIGHT_ATTENUATION(attenuation, input, input.posWorld.xyz);`
Hope that helps someone. Cheers!

**Comment by traggett** [comment]
Ah awesome thanks for the tip! Hey do you work for Unity? I wondering if you could maybe help with a Sprite lighting problem I encountered when making these shaders..

So in order for normal maps to work on Sprite Renderers they obv need to caluclate the binormals correctly.
However! If a SpriteRenderer is set to 'Flip X' or 'Flip Y' then the binormals also need to be flipped but there appears now way of the shader knowing the sprite is flipped (the usual method is using unity_WorldTransformParams but unity_WorldTransformParams.w isn't set to -1).

I found a bug which says unity_WorldTransformParams.w is not changing for Sprites and its closed and marked By Design:
https://issuetracker.unity3d.com/issues/unity-worldtransformparams-dot-w-do-not-work-with-sprites

If it's by design then what is the design or method recommended for correctly calculating binormals for negatively scaled or flipped SpriteRenderers? Is they any way of the shaders knowing a Sprite is flipped?

Thanks a lot!

**Comment by jkampitakis** [comment]
Hello,
the first argument "attenuation" is unknown.. 
How can we fix this?

**Comment by traggett** [comment]
Hey, what version of Unity are you using?

**Comment by jkampitakis** [comment]
2018.1.6f1

I managed to make it work.

Thanks.

**Comment by traggett** [comment]
OK cool, let me know if you found a bug though!
Cheers :)
