### ISSUE TITLE
Work in editor, but doesn't in Standalone build

### ISSUE THREAD

**Issue by Mihail5412** [traggett/UnitySpriteShaders#16]
Hello.
I ran into the following problem:

My object is created in realtime, and i cant configure it through the inspector in advance. In fact, I can not even copy my object in prefab, since its mesh is created at runtime.
So i need to change the parameters using the code. I rummaged through the script for the editor (SpriteShaderGUI) and took a couple of functions from there.
As a result, my configuration code looks like this:
```
SetBlendMode(material, eBlendMode.StandardAlpha);
material.SetTexture("_BumpMap", GameObject.Find("TestObject").GetComponent<Res>().normalMap);
material.SetFloat("_ShadowAlphaCutoff", 0.635f);
material.SetFloat("_Cutoff", 0.6f);
material.SetFloat("_ZWrite", 1.0f);
SetMaterialKeywords(material);
```
As a result, everything is perfect in the editor. The shader is configured and i can safely work, but in the standalone build for Windows the parameters seem to be not applied and the object itself becomes very dark.

Perhaps this is due to the fact that I do not include the Pixel Lit shader in Graphics-> Always Included Shaders, but I throw it in ShaderVariants, since if i throw it in Always Included Shaders, then I get this madness:
![image](https://user-images.githubusercontent.com/31993946/41801867-c12685d4-7685-11e8-9600-9415bbbfb9e3.png)

**Comment by traggett** [comment]
Hey um I confused what you're trying to do. It doesn't matter if your mesh is created at runtime, surely you just create a material from it in the editor and apply that material at runtime no? Like configure the shader on a material rather than a mesh and then apply that material to the mesh at runtime?

I would advise against setting keywords at runtime, instead swap materials if you want to dynamically turn Z Writing off. 
Otherwise yeah its going to have to compile a new version of the shader at runtime.

**Comment by Mihail5412** [comment]
Thank you. I decided the problem.
You see, the thing was that I do not really understand the shader settings. I took a more detailed look at your script (SpriteShaderGUI) and took from there those tuning functions that I needed (for convenience I created a new class) and applied all the settings to the materials in Awake.
Everything works fine and this does not affect performance.
Thank you for a very cool shader !!!!
